# -*- coding: utf-8 -*-
"""practical 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAVtQbN-fccOgANNCsv6kyuilKKJMoeK
"""

a=10
print(type(a))
print (id(a))

num=a
print(id(a))

num=20
print(id(num))

for row in range(1,5):
  for col in range(1,row+1):
    print("*",end=" ")
  print()

for i in range(1,4):
  for j in range(1,4):
    print(i,end=" ")
  print()

n=4
for i in range(1,4):
  for j in range(1,5):
    print(n,end=" ")
  n-=1
  print()

n=10
x=2
for i in range(x):
  for j in range(x+1):
    print(n,end=" ")
    n+=1
  print()

n=4
for i in range(1,5):
  for j in range(i,5):
    print(n,end=" ")
  n-=1
  print()

for i in range(1,5):
  for i in range(5,i,-1):
    print("*",end=" ")
  print()

for i in range(1,5):
  n=1
  for j in range(i,5):
    print(n,end=" ")
    n+=1
  print()

a=65
for i in range(1,5):
  for j in range(i,5):
    print(chr(a),end=" ")
  a+=1
  print()

# ord("A")
#ord to print ASCII values
#chr to print character based ASCII values

n=5
for i in range(1,n+1):
  num=65
  for j in range(i,n+1):
    print(chr(num),end=" ")
    num+=1
  print()

a=20
for i in range(1,4):
  for i in range(i,5):
    print(a,end=" ")
    a+=1
  print()

z=90
for i in range(1,4):
  for i in range(i,4):
    print(chr(z),end=" ")
  z-=1
  print()

for i in range(1,5):
  for j in range(1,i+1):
    print("*",end=" ")
  print()
for i in range(1,4):
  for j in range(i,4):
    print("*",end=" ")
  print()

d=68
for i in range(1,5):
  for j in range(1,i+1):
    print(chr(d),end=" ")
    d+=1
  print()

a=4
for i in range(1,4):
  for j in range(1,i+1):
    print(a)

for i in range(1,5):
  for s in range(i):
    print(" ",end=" ")
  for j in range(i,5):
    print("*",end=" ")
  print()
for i in range(1,5):
  for s in range(i,5):
    print(" ",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print()